{% set name = "autogluon.core" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd

build:
  # noarch: python
  skip: True  # [py>=310]
  script: {{ PYTHON }} -m pip install ./core -vv
  number: 3
  script_env:
   - RELEASE=1

requirements:
  # adds osx_arm64 builds. See https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python # >=3.7,<3.10
    - pip
  run:
    - python # >=3.7,<3.10
    - numpy <1.24,>=1.21
    - scipy <1.10.0,>=1.5.4
    - scikit-learn <1.2,>=1.0.0
    - psutil <6,>=5.7.3
    - networkx <3.0,>=2.3
    - pandas !=1.4.0,<1.6,>=1.2.5
    - tqdm >=4.38.0
    - requests
    - matplotlib-base
    - dask-core <=2021.11.2,>=2021.09.1
    - distributed <=2021.11.2,>=2021.09.1
    - boto3
    - ray-default  # [not osx]
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.core
  commands:
    - python -c "from autogluon.core import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip

about:
  home: https://pypi.org/project/autogluon.core
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
